apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: todo_app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GO_PORT
          value: "8080"
        - name: IMAGE_URL
          value: "https://picsum.photos/1200"
        - name: IMAGE_PATH
          value: /usr/src/shared/files/picsum.png
        volumeMounts:
          - name: persistent
            mountPath: /usr/src/shared/files
      - name: todo-backend
        image: todo_backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: BACK_PORT
          value: "8081"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
      volumes:
      - name: persistent
        persistentVolumeClaim:
          claimName: todo-pvc