apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- Deployment.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- postgres-deployment.yaml
- postgres-secret.yaml
- postgres-service.yaml
- secret.yaml
- service.yaml
images:
  - name: todo_app
    newName:
  - name: todo_backend
    newName: 
