apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  selector:
    matchLabels:
      app: todo
  template:
    spec:
      containers:
      - name: todo-broadcaster
        env:
        - name: DISCORD_URL
          value: https://discord.com/api/webhooks/1272216427230924950/PwMo1VfloOWfUk33xrfqGLrulFqQubTPi_wg8hR2KERUUDp4bc7VeDotPMYJjoxNP3d5
      volumes:
      - name: persistent
        persistentVolumeClaim:
          claimName: todo-pvc