apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logoutput-pvc
  namespace: logoutput
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi