kind: Service
apiVersion: v1
metadata:
  name: todo-svc
  namespace: todo
spec:
  selector:
    app:  todo
  type:  ClusterIP
  ports:
  - port: 8080
    targetPort:  8080
---
kind: Service
apiVersion: v1
metadata:
  name: todo-backend-svc
  namespace: todo
spec:
  selector:
    app:  todo
  type:  ClusterIP
  ports:
  - port: 8081
    targetPort:  8081
