apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
  namespace: todo
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi