apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo
  labels:
    app: postgres
stringData:
  DATABASE_URL: postgres://ps_user:strongpass0000@postgres.todo.svc.cluster.local:5432/ps_db?sslmode=disable

