apiVersion: batch/v1 # Correct API version for CronJob
kind: CronJob 
metadata:
  name: backup # Metadata with name
spec:
  schedule: "0 0 * * *" # Correct cron schedule string
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: ubuntu:latest
            command: ["/bin/bash", "/tmp/backup_pg_dump.sh"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-postgres-secret
                  key: DATABASE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: API_KEY
            volumeMounts:
              - name: backup-config
                mountPath: /tmp/
                subPath: backup_pg_dump.sh
          restartPolicy: OnFailure
        volumes:
        - name: backup-config
          configMap:
            name: backup-config
