kind: Service
apiVersion: v1
metadata:
  name: todo-svc
  namespace: todo
spec:
  selector:
    app:  todo
  type:  NodePort
  ports:
  - name: http
    nodePort:  30080
    protocol: TCP
    port: 8080
    targetPort:  8080