apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pingpong-logoutput
  labels:
    app: postgres
stringData:
  DATABASE_URL: postgres://ps_user:strongpass0000@postgres.postgres.svc.cluster.local:5432/ps_db?sslmode=disable

