apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
  namespace: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
      - name: logoutput-reader
        image: astranero/logoutput-reader:2.06
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: logoutput
                key: MESSAGE
        volumeMounts:
          - name:  config
            mountPath:  "/config"
      - name: pingpong
        image: astranero/pingpong:2.02
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
      volumes:
        - name: config 
          configMap: 
            name: logoutput
