kind: Service
apiVersion: v1
metadata:
  name: logoutput-svc
  namespace: logoutput
spec:
  selector:
    app:  logoutput
  type:  ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort:  8080
---
kind: Service
apiVersion: v1
metadata:
  name: pong-svc
  namespace: logoutput
spec:
  selector:
    app:  logoutput
  type:  ClusterIP
  ports:
  - port: 8081
    protocol: TCP
    targetPort:  8081
