apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
data:
  backup_pg_dump.sh: | 
    #!/bin/bash
    set -e
    if [ $DATABASE_URL ]
    then
      pg_dump -v $DATABASE_URL > ~/backup.sql
      curl -X PUT --data-binary @~/backup.sql -H "Authorization: Bearer $API_KEY" -H "Content-Type: text/plain " https://storage.googleapis.com/upload/storage/v1/b/gke-dwe/o?uploadType=media&name=postgres-backup"
    fi
---
