apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: astranero/todo-projectv.07:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        volumeMounts:
          - name: persistent
            mountPath: /usr/src/shared/files
      volumes:
      - name: persistent
        persistentVolumeClaim:
          claimName: todo-pvc