name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  FRONTEND_IMAGE: todo_app
  FRONTEND_SERVICE: todo_app
  BACKEND_IMAGE: todo_backend
  BACKEND_SERVICE: todo_backend
  BRANCH: ${{ github.ref_name }}
  
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
      
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v2

    - name: 'Use gcloud CLI'
      run: gcloud info

    - name: Docker configuration
      run: gcloud --quiet auth configure-docker
      
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}

    # Build the Docker images
    - name: Build Backend Docker image
      run: |-
        docker build \
          --tag "gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}" \
          "./Project v.1.4/${{ env.BACKEND_IMAGE }}"

    - name: Build Frontend Docker image
      run: |-
        docker build \
          --tag "gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}" \
          "./Project v.1.4/${{ env.FRONTEND_IMAGE }}"
  
    # Push the Docker images to Google Container Registry
    - name: Publish Backend Docker image
      run: |-
        docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}" 

    - name: Publish Frontend Docker image
      run: |-
        docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}"
      
    - name: Install Kustomize
      run: |-
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        mv kustomize /usr/local/bin/
    
    - name: Deploy
      run: |-
        mkdir kustomize-temp
        cp -r "./Project v.1.4/manifests/." kustomize-temp/
        cd kustomize-temp

        ../kustomize edit set image ${{ env.FRONTEND_IMAGE }}="gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}" 
        ../kustomize edit set image ${{ env.BACKEND_IMAGE }}="gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}" 

        ../kustomize build . | kubectl apply -f -
        
        kubectl rollout status deployment/${{ env.FRONTEND_SERVICE }}
        kubectl rollout status deployment/${{ env.BACKEND_SERVICE }}
        
        # Get the services information
        kubectl get services -o wide

